version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python src/main.py"
    devices:
      - "/dev/snd:/dev/snd"
